config/routes.rb
Rails.application.routes.draw do
  
  resources :innings
  #get 'match_players/index'

  #get 'match_players/show'

  get 'fixtures/index'

  get 'fixtures/show'
  
  get 'matches/all', to: 'matches#all'

  resources :matches
  resources :rounds
  # resources :comp_rounds
  resources :competitions, shallow: true do
    resources :rounds do
      resources :fixtures do
        resources :matches do
          resources :innings do
          
          end
        end  
      end
    end
  end
  resources :players
  resources :teams

  resources :clubs, shallow: true do
    resources :teams do
      resources :players
    end
    resources :players
  end
  resources :keywords
  #get 'static_pages/welcome'
  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    validates :name, :street_address, :street_city, :street_state, :phone, :email, presence: true
    mount_uploader :logo, LogoUploader

    has_many :teams
    has_many :players

    def display_address
      if self.street_address != nil then
        return self.street_address.to_s + ", " + self.street_city.to_s + ", " + self.street_state.to_s + ", " + self.street_postcode.to_s
      end
    end
    def display_post_address
      if self.postal_address != nil then
        return self.postal_address + ", " + self.postal_city + ", " + self.postal_state + ", " + self.postal_postcode
      end
    end
end

app/models/competition.rb
class Competition < ApplicationRecord
    validates :name, :start_date, :end_date, :match_days, presence: true

    has_many :rounds, inverse_of: :competition
    # has_many :matches
end

app/models/fixture.rb
class Fixture < ApplicationRecord
    validates :grade, :home_team, :away_team, presence: true
    
    belongs_to :round, inverse_of: :fixtures
    has_many :matches, inverse_of: :fixture
end

app/models/inning.rb
class Inning < ApplicationRecord
  validates :inning_no, :batting_team, :bowling_team, presence: true  
  
  belongs_to :match, inverse_of: :innings
  #has_many :overs
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :key_type, :key_value, presence: true

  def by_key(key)
      AdminKeyword.find_each do |keyword|
          keyword.find_by key_type: (key)
      end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :fixture, inverse_of: :matches
  
  has_many :innings
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
    validates :name, presence: true
    
    belongs_to :match
end

app/models/player.rb
class Player < ApplicationRecord
  validates :first_name, :last_name, :full_name, :display_name, :phone, :email, presence: :true

  belongs_to :club
  belongs_to :team

  # def club_name
  #   return Club.find_by_id(self.club_id).name
  # end
end

app/models/round.rb
class Round < ApplicationRecord
  validates :round_no, :start_date, :end_date, presence: true
  
  belongs_to :competition, inverse_of: :rounds
  has_many :fixtures, dependent: :destroy, inverse_of: :round
  accepts_nested_attributes_for :fixtures
  
  def all_matches
    self.fixtures.each do |fix|
      return fix.matches
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, :grade, presence: true

  belongs_to :club
  has_many :players
  
  # def club_name
  #   return Club.find(self.club_id).name
  # end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :start_date, :end_date, :match_days, :limited_overs, :restrict_bowl, :restrict_bat, :restrict_field, :points_win, :points_draw, :points_lose, :allow_bonus, :bonus_criteria, :points_bonus, :max_overs, :max_bowler_overs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def yesno_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/innings_helper.rb
module InningsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/competitions/_form.html.erb
<%= render layout: 'layouts/sidemenu' do %>
  <%= form_with(model: competition, local: true) do |form| %>
    <% if competition.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

        <ul>
        <% competition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="actions">
    <%= form.submit "Save", class: 'ui small blue button' %>
    <%= link_to "Cancel", competitions_path, class:"ui small red button" %>
  </div>
  <div class="ui form">
    <div class="nine wide field">
      <%= form.label :name, class: 'label' %>
      <%= form.text_field :name, id: 'competition_name' %>
    </div>
    <div class="three fields">
      <div class="three wide field">
        <%= form.label :start_date, class: 'label' %>
        <%= form.text_field :start_date, id: 'competition_start_date' %>
      </div>
      <div class="three wide field">
        <%= form.label :end_date, class: 'label' %>
        <%= form.text_field :end_date, id: 'competition_end_date' %>
      </div>
      <div class="three wide field">
        <%= form.label :match_days, 'No of Days for Match', class: 'label' %>
        <%= form.text_field :match_days, id: 'competition_match_days' %>
      </div>
    </div>
    <div class="field">
      <%= form.label :limited_overs, 'Limited Overs?', class: 'label' %>
      <%= form.check_box :limited_overs, class: 'ui checkbox', id: 'competition_limited_overs' %>
    </div>
    <div class="two fields" id="limited_over_details">
      <div class="three wide field">
        <%= form.label :max_overs, 'Maximum Overs', class: 'label' %>
        <%= form.text_field :max_overs, id: 'competition_max_overs' %>
      </div>
      <div class="three wide field">
        <%= form.label :max_bowler_overs, 'Maximum Overs per Bowler', class: 'label' %>
        <%= form.text_field :max_bowler_overs, id: 'competition_max_bowler_overs' %>
      </div>
    </div>
    <div class="nine wide field">
      <%= form.label :restrict_bat, 'Batting Restrictions', class: 'label' %>
      <%= form.text_field :restrict_bat, id: 'competition_restrict_bat' %>
    </div>
    <div class="nine wide field">
      <%= form.label :restrict_bowl, 'Bowling Restrictions', class: 'label' %>
      <%= form.text_field :restrict_bowl, id: 'competition_restrict_bowl' %>
    </div>
    <div class="nine wide field">
      <%= form.label :restrict_field, 'Fielding Restrictions', class: 'label' %>
      <%= form.text_field :restrict_field, id: 'competition_restrict_field' %>
    </div>
    <div class="three fields">
      <div class="three wide field">
        <%= form.label :points_win, 'Points for Win', class: 'label' %>
        <%= form.text_field :points_win, id: 'competition_points_win' %>
      </div>
      <div class="three wide field">
        <%= form.label :points_draw, 'Points for Draw', class: 'label' %>
        <%= form.text_field :points_draw, id: 'competition_points_draw' %>
      </div>
      <div class="three wide field">
        <%= form.label :points_lose, 'Points for Loss', class: 'label' %>
        <%= form.text_field :points_lose, id: 'competition_points_lose' %>
      </div>
    </div>
    <div class="field">
      <%= form.label :allow_bonus, 'Allow Bonus Points?', class: 'label' %>
      <%= form.check_box :allow_bonus, class: 'ui checkbox', id: 'competition_allow_bonus' %>
    </div>
    <div class="two fields" id="bonus_points_details">
      <div class="six wide field">
        <%= form.label :bonus_criteria, 'Criteria for Bonus Points', class: 'label' %>
        <%= form.text_field :bonus_criteria, id: 'competition_bonus_criteria' %>
      </div>
      <div class="three wide field">
        <%= form.label :points_bonus, 'Bonus Points', class: 'label' %>
        <%= form.text_field :points_bonus, id: 'competition_points_bonus' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/competitions/edit.html.erb
<%= render 'form', competition: @competition %>

app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>
<%= render layout: 'layouts/sidemenu' do %>
  <h3 class="grey ui header">
      <i class="globe icon"></i>
      <div class="content">Competitions</div>
  </h3>
  <span><%= link_to "New", new_competition_path, class: "ui small blue button" %></span>
  <table class="ui very basic table">
        <thead>
            <tr>
              <th>Competition</th>
              <th>Start date</th>
              <th>End date</th>
              <th>Rounds</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            <% @competitions.each do |competition| %>
                <tr>
                    <td><%= link_to competition.name, competition, class: 'inline-link' %></td>
                    <td><%= competition.start_date.to_formatted_s(:rfc822) %></td>
                    <td><%= competition.end_date.to_formatted_s(:rfc822) %></td>
                    <td>
                      <%= link_to "Fixtures", competition_rounds_path(competition.id), class: "ui tiny teal button" %>
                      <%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' }, class:'ui tiny red button' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

<% end %>

app/views/competitions/new.html.erb
<%= render 'form', competition: @competition %>

app/views/competitions/show.html.erb
<%= render layout: 'layouts/sidemenu' do %>
  <h3 class="grey ui header">
    <i class="user icon"></i>
    <div class="content">Competition Details</div>
  </h3>
  <div class='action-glyphs'>
    <span><%= link_to "Fixtures", competition_rounds_path(@competition.id), class: "ui teal button" %></span>
    <span><%= link_to "Edit", edit_competition_path(@competition), class: "ui blue button" %></span>
    <span><%= link_to "Cancel", competitions_path, class:"ui red button" %></span>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="ui form">
    <div class="seven wide field">
      <label>Competition Name</label>
      <%= @competition.name %>
    </div>
    <div class="three fields">
      <div class="three wide field">
        <label>Start date</label>
        <%= @competition.start_date.to_formatted_s(:rfc822) %>
      </div>
      <div class="three wide field">
        <label>End date</label>
        <%= @competition.end_date.to_formatted_s(:rfc822) %>
      </div>
      <div class="two wide field">
        <label>No of Days for Match</label>
        <%= @competition.match_days %>
      </div>
    </div>
    <div class="field">
      <label>Limited Overs?</label>
      <span id="limited_overs"><%= yesno_boolean(@competition.limited_overs) %></span>
    </div>
    <div class="two fields" id="limited_over_details">
      <div class="three wide field">
        <label>Maximum Overs</label>
        <%= @competition.max_overs %>
      </div>
      <div class="three wide field">
        <label>Maximum Overs per Bowler</label>
        <%= @competition.max_bowler_overs %>
      </div>
    </div>
    <div class="field">
      <label>Batting Restrictions</label>
      <%= @competition.restrict_bat %>
    </div>
    <div class="field">
      <label>Bowling Restrictions</label>
      <%= @competition.restrict_bowl %>
    </div>
    <div class="field">
      <label>Fielding Restrictions</label>
      <%= @competition.restrict_field %>
    </div>
    <div class="three fields">
      <div class="three wide field">
        <label>Points for Win</label>
        <%= @competition.points_win %>
      </div>
      <div class="three wide field">
        <label>Points for Draw</label>
        <%= @competition.points_draw %>
      </div>
      <div class="two wide field">
        <label>Points for Loss</label>
        <%= @competition.points_lose %>
      </div>
    </div>
    <div class="field">
      <label>Allow Bonus Points?</label>
      <span id="allow_bonus"><%= yesno_boolean(@competition.allow_bonus) %></span>
    </div>
    <div class="two fields" id="bonus_points_details">
      <div class="six wide field">
        <label>Criteria for Bonus Points</label>
        <%= @competition.bonus_criteria %>
      </div>
      <div class="three wide field">
        <label>Bonus Points</label>
        <%= @competition.points_bonus %>
      </div>
    </div>
  </div>
<% end %>