config/routes.rb
Rails.application.routes.draw do
  
  resources :innings
  #get 'match_players/index'

  #get 'match_players/show'

  get 'fixtures/index'

  get 'fixtures/show'
  
  get 'matches/all', to: 'matches#all'

  resources :matches
  resources :rounds
  # resources :comp_rounds
  resources :competitions, shallow: true do
    resources :rounds do
      resources :fixtures do
        resources :matches do
          resources :innings do
          
          end
        end  
      end
    end
  end
  resources :players
  resources :teams

  resources :clubs, shallow: true do
    resources :teams do
      resources :players
    end
    resources :players
  end
  resources :keywords
  #get 'static_pages/welcome'
  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    validates :name, :street_address, :street_city, :street_state, :phone, :email, presence: true
    mount_uploader :logo, LogoUploader

    has_many :teams
    has_many :players

    def display_address
      if self.street_address != nil then
        return self.street_address.to_s + ", " + self.street_city.to_s + ", " + self.street_state.to_s + ", " + self.street_postcode.to_s
      end
    end
    def display_post_address
      if self.postal_address != nil then
        return self.postal_address + ", " + self.postal_city + ", " + self.postal_state + ", " + self.postal_postcode
      end
    end
end

app/models/competition.rb
class Competition < ApplicationRecord
    validates :name, :start_date, :end_date, :match_days, presence: true

    has_many :rounds, inverse_of: :competition
    # has_many :matches
end

app/models/fixture.rb
class Fixture < ApplicationRecord
    validates :grade, :home_team, :away_team, presence: true
    
    belongs_to :round, inverse_of: :fixtures
    has_many :matches, inverse_of: :fixture
end

app/models/inning.rb
class Inning < ApplicationRecord
  validates :inning_no, :batting_team, :bowling_team, presence: true  
  
  belongs_to :match, inverse_of: :innings
  #has_many :overs
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :key_type, :key_value, presence: true

  def by_key(key)
      AdminKeyword.find_each do |keyword|
          keyword.find_by key_type: (key)
      end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :fixture, inverse_of: :matches
  
  has_many :innings
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
    validates :name, presence: true
    
    belongs_to :match
end

app/models/player.rb
class Player < ApplicationRecord
  validates :first_name, :last_name, :full_name, :display_name, :phone, :email, presence: :true

  belongs_to :club
  belongs_to :team

  # def club_name
  #   return Club.find_by_id(self.club_id).name
  # end
end

app/models/round.rb
class Round < ApplicationRecord
  validates :round_no, :start_date, :end_date, presence: true
  
  belongs_to :competition, inverse_of: :rounds
  has_many :fixtures, dependent: :destroy, inverse_of: :round
  accepts_nested_attributes_for :fixtures
  
  def all_matches
    self.fixtures.each do |fix|
      return fix.matches
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, :grade, presence: true

  belongs_to :club
  has_many :players
  
  # def club_name
  #   return Club.find(self.club_id).name
  # end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    session[:comp_id]= params[:competition_id]
    @round = Round.new
    @round.competition_id = session[:comp_id]
    @round.fixtures.build
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
    @fixtures = @round.fixtures
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @round.competition_id = session[:comp_id]

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @comp_id = @round.competition_id
    @round.destroy
    respond_to do |format|
      format.html { redirect_to competition_rounds_path(@comp_id), notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:round_no, :start_date, :end_date, :competition_id, fixtures_attributes: [:id, :home_team, :away_team, :ground, :grade, :round_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def yesno_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/innings_helper.rb
module InningsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/rounds/_fixture_details.html.erb
    <div class="four fields">
        <div class="two wide field">
            <%= f.text_field :grade, id: 'fixture_grade' %>
        </div>
        <div class="two wide field">
            <%= f.text_field :home_team, id: 'fixture_home_team' %>
        </div>
        <div class="two wide field">
            <%= f.text_field :away_team, id: 'fixture_away_team' %>
        </div>
        <div class="two wide field">
            <%= f.text_field :ground, id: 'fixture_ground' %>
        </div>
        <div class="four wide field">
            <%= link_to_remove_association 'Remove', f, class: 'ui tiny red button' %>
        </div>
    </div>

app/views/rounds/_form.html.erb
<%= render layout: 'layouts/sidemenu' do %>
  <%= form_with(model: round, local: true) do |form| %>
    <% if round.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

        <ul>
        <% round.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="actions">
      <%= form.submit "Save", class: 'ui small blue button' %>
      <%= link_to "Cancel", competitions_path, class:"ui small red button" %>
    </div>
    <div class="ui form">
      <div class="two wide field">
        <%= form.label :round_no, class: 'label' %>
        <%= form.text_field :round_no, id: 'round_round_no' %>
      </div>
    <div class="two fields">
      <div class="three wide field">
        <%= form.label :start_date, class: 'label' %>
        <%= form.text_field :start_date, id: 'round_start_date' %>
      </div>
      <div class="three wide field">
        <%= form.label :end_date, class: 'label' %>
        <%= form.text_field :end_date, id: 'round_end_date' %>
      </div>
    </div>
    <div class="ui raised segment">
      <div class="four fields">
        <div class="two wide field">Grade</div>
        <div class="two wide field">Home Team</div>
        <div class="two wide field">Away Team</div>
        <div class="two wide field">Ground</div>
        <div class="eight wide field"><%= link_to_add_association 'Add Fixtures', form, :fixtures, partial: 'rounds/fixture_details', class: 'ui small blue button', data: { association_insertion_method: :append,  association_insertion_node: '#detail_body'} %></div>
      </div>
      <div class="ui divider"></div>
      <div id="detail_body">
        <%= form.fields_for :fixtures do |dtl| %>
          <%= render 'fixture_details', :f => dtl %>
        <% end %>
      </div>

    </div>
  <% end %>
<% end %>

app/views/rounds/edit.html.erb
<%= render 'form', round: @round %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>
<%= render layout: 'layouts/sidemenu' do %>
  <h3 class="grey ui header">
      <i class="globe icon"></i>
      <div class="content">Competitions</div>
  </h3>
  <span><%= link_to "New", new_competition_round_path(params[:competition_id]), class: "ui small blue button" %></span>
  <table class="ui very basic table">
    <tbody>
      <% @rounds.each do |round| %>
        <tr>
          <td colspan='7'>
            <div class="ui accordion field">
              <div class="title">
                <i class="icon dropdown"></i>
                  Round <%= round.round_no %>
              </div>
              <div class="content field">
                <table class="ui very basic table">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Start date</th>
                      <th>End date</th>
                      <th class="two wide">Grade</th>
                      <th class="two wide">Home Team</th>
                      <th class="two wide">Away Team</th>
                      <th class="two wide">Ground</th>
                      <th class="two wide"></th>
                      <th colspan="2"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td></td>
                      <td style="vertical-align: top;" class="two wide"><%= round.start_date.to_formatted_s(:rfc822) %></td>
                      <td style="vertical-align: top;" class="two wide"><%= round.end_date.to_formatted_s(:rfc822) %></td>
                      <td colspan="5" style="vertical-align: top; padding: 0 0 0 0;">
                        <table class="ui very basic compact table">
                          <% round.fixtures.each do |fix| %>
                            <tr>
                              <td style="vertical-align: top;padding-left: 10px;" class="two wide"><%= fix.grade %></td>
                              <td style="vertical-align: top;" class="two wide"><%= fix.home_team %></td>
                              <td style="vertical-align: top;" class="two wide"><%= fix.away_team %></td>
                              <td style="vertical-align: top;" class="two wide"><%= fix.ground %></td>
                              <td style="vertical-align: top;" class="two wide"><%= link_to 'Create Match', new_fixture_match_path(fix.id), class: "ui tiny green button" %></td>
                            </tr>
                          <% end %>
                        </table>
                      </td>
                      <td style="vertical-align: top;" class="one wide"><%= link_to 'Edit', edit_round_path(round), class: "ui tiny blue button" %></td>
                      <td style="vertical-align: top;" class="three wide"><%= link_to 'Delete', round, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui tiny red button" %></td>
                    </tr>
                  </tbody>

                </table>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/rounds/new.html.erb
<%= render 'form', round: @round %>

app/views/rounds/show.html.erb
<%= render layout: 'layouts/sidemenu' do %>
  <h3 class="grey ui header">
    <i class="user icon"></i>
    <div class="content">Round Details</div>
  </h3>
  <div class='action-glyphs'>
    <span><%= link_to "Edit", edit_round_path(@round), class: "ui blue button" %></span>
    <span><%= link_to "Cancel", competitions_path, class:"ui red button" %></span>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="ui form">
    <div class="three wide field">
      <label>Round No</label>
      <%= @round.round_no %>
    </div>
    <div class="two fields">
      <div class="three wide field">
        <label>Start date</label>
        <%= @round.start_date.to_formatted_s(:rfc822) %>
      </div>
      <div class="three wide field">
        <label>End date</label>
        <%= @round.end_date.to_formatted_s(:rfc822) %>
      </div>
    </div>
  </div>
<% end %>