config/routes.rb
Rails.application.routes.draw do
  
  resources :innings
  #get 'match_players/index'

  #get 'match_players/show'

  get 'fixtures/index'

  get 'fixtures/show'
  
  get 'matches/all', to: 'matches#all'

  resources :matches
  resources :rounds
  # resources :comp_rounds
  resources :competitions, shallow: true do
    resources :rounds do
      resources :fixtures do
        resources :matches do
          resources :innings do
          
          end
        end  
      end
    end
  end
  resources :players
  resources :teams

  resources :clubs, shallow: true do
    resources :teams do
      resources :players
    end
    resources :players
  end
  resources :keywords
  #get 'static_pages/welcome'
  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    validates :name, :street_address, :street_city, :street_state, :phone, :email, presence: true
    mount_uploader :logo, LogoUploader

    has_many :teams
    has_many :players

    def display_address
      if self.street_address != nil then
        return self.street_address.to_s + ", " + self.street_city.to_s + ", " + self.street_state.to_s + ", " + self.street_postcode.to_s
      end
    end
    def display_post_address
      if self.postal_address != nil then
        return self.postal_address + ", " + self.postal_city + ", " + self.postal_state + ", " + self.postal_postcode
      end
    end
end

app/models/competition.rb
class Competition < ApplicationRecord
    validates :name, :start_date, :end_date, :match_days, presence: true

    has_many :rounds, inverse_of: :competition
    # has_many :matches
end

app/models/fixture.rb
class Fixture < ApplicationRecord
    validates :grade, :home_team, :away_team, presence: true
    
    belongs_to :round, inverse_of: :fixtures
    has_many :matches, inverse_of: :fixture
end

app/models/inning.rb
class Inning < ApplicationRecord
  validates :inning_no, :batting_team, :bowling_team, presence: true  
  
  belongs_to :match, inverse_of: :innings
  #has_many :overs
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :key_type, :key_value, presence: true

  def by_key(key)
      AdminKeyword.find_each do |keyword|
          keyword.find_by key_type: (key)
      end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :fixture, inverse_of: :matches
  
  has_many :innings
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
    validates :name, presence: true
    
    belongs_to :match
end

app/models/player.rb
class Player < ApplicationRecord
  validates :first_name, :last_name, :full_name, :display_name, :phone, :email, presence: :true

  belongs_to :club
  belongs_to :team

  # def club_name
  #   return Club.find_by_id(self.club_id).name
  # end
end

app/models/round.rb
class Round < ApplicationRecord
  validates :round_no, :start_date, :end_date, presence: true
  
  belongs_to :competition, inverse_of: :rounds
  has_many :fixtures, dependent: :destroy, inverse_of: :round
  accepts_nested_attributes_for :fixtures
  
  def all_matches
    self.fixtures.each do |fix|
      return fix.matches
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, :grade, presence: true

  belongs_to :club
  has_many :players
  
  # def club_name
  #   return Club.find(self.club_id).name
  # end
end

app/controllers/innings_controller.rb
class InningsController < ApplicationController
  before_action :set_inning, only: [:show, :edit, :update, :destroy]

  # GET /innings
  # GET /innings.json
  def index
    @innings = Inning.all
  end

  # GET /innings/1
  # GET /innings/1.json
  def show
  end

  # GET /innings/new
  def new
    @inning = Inning.new
    @inning.match_id = params[:match_id]
  end

  # GET /innings/1/edit
  def edit
  end

  # POST /innings
  # POST /innings.json
  def create
    @inning = Inning.new(inning_params)

    respond_to do |format|
      if @inning.save
        format.html { redirect_to @inning, notice: 'Inning was successfully created.' }
        format.json { render :show, status: :created, location: @inning }
      else
        format.html { render :new }
        format.json { render json: @inning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /innings/1
  # PATCH/PUT /innings/1.json
  def update
    respond_to do |format|
      if @inning.update(inning_params)
        format.html { redirect_to @inning, notice: 'Inning was successfully updated.' }
        format.json { render :show, status: :ok, location: @inning }
      else
        format.html { render :edit }
        format.json { render json: @inning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /innings/1
  # DELETE /innings/1.json
  def destroy
    @inning.destroy
    respond_to do |format|
      format.html { redirect_to match_innings_url(@inning.match_id), notice: 'Inning was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inning
      @inning = Inning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inning_params
      params.require(:inning).permit(:inning_no, :batting_team, :bowling_team, :runs, :wickets, :byes, :legbyes, :no_balls, :wides, :score, :match_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def yesno_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/innings_helper.rb
module InningsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/innings/_form.html.erb
<%= form_with(model: inning, local: true) do |form| %>
  <% if inning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inning.errors.count, "error") %> prohibited this inning from being saved:</h2>

      <ul>
      <% inning.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <table class="ui attached very compact celled table" id="graph_table">
        <tbody>
          <tr id="graph-collapse-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="graph_collapse"><i class="large inverted white caret square up outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Overs</td>
          </tr>
          <tr id="graph-expand-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="graph_expand"><i class="large inverted white caret square down outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Overs</td>
          </tr>
          <tr id="graph_details_row">
            <td colspan=2>
              
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="ui grid">
    <div class="ui sixteen wide column">
        <table class="ui attached very compact celled table" id="inning_details_table">
          <tbody>
            <tr id="details-collapse-row" class="detail_header_row">
              <td class="one wide"><a class="no-link" id="details_collapse"><i class="large inverted white caret square up outline icon"></i></a></td>
              <td colspan=13 class="detail_header_text">Inning Details</td>
            </tr>
            <tr id="details-expand-row" class="detail_header_row">
              <td class="one wide"><a class="no-link" id="details_expand"><i class="large inverted white caret square down outline icon"></i></a></td>
              <td colspan=13 class="detail_header_text">Inning Details</td>
            </tr>
            <tr id="inning_details_row1">
              <td class="detail_label">Round</td>
              <td class="one wide"><%= @inning.match.fixture.round.round_no %></td>
              <td class="detail_label">Start</td>
              <td class="two wide"><%= @inning.match.fixture.round.start_date.to_formatted_s(:rfc822) %></td>
              <td class="detail_label">Finish</td>
              <td class="two wide"><%= @inning.match.fixture.round.end_date.to_formatted_s(:rfc822) %></td>
              <td class="detail_label">Grade</td>
              <td class="two wide"><%= @inning.match.fixture.grade %></td>
              <td class="detail_label">Home</td>
              <td class="three wide"><%= @inning.match.fixture.home_team %></td>
              <td class="detail_label">Away</td>
              <td class="three wide"><%= @inning.match.fixture.away_team %></td>
              <td class="detail_label">Ground</td>
              <td class="three wide"><%= @inning.match.fixture.ground %></td>
            </tr>
            <tr id="inning_details_row2">
              <td class="detail_label">Toss</td>
              <td colspan=3></td>
              <td class="detail_label">Umpire</td>
              <td><%= @inning.match.referee1 %></td>
              <td class="detail_label">Umpire</td>
              <td><%= @inning.match.referee2 %></td>
              <td class="detail_label">Scorer</td>
              <td><%= @inning.match.scorer %></td>
              <td class="detail_label">Result</td>
              <td colspan=3><%= @inning.match.result %></td>
            </tr>
            <tr class="ui form" id="inning_details_row3">
              <td class="detail_label">Inning</td>
              <td colspan=3><%= form.text_field :inning_no, id: 'inning_inning_no', class: 'ui mini input' %></td>
              <td class="detail_label">Batting</td>
              <td colspan=3><%= form.text_field :batting_team, id: 'inning_batting_team', class: 'ui mini input' %></td>
              <td class="detail_label">Bowling</td>
              <td colspan=3><%= form.text_field :bowling_team, id: 'inning_bowling_team', class: 'ui mini input' %></td>
              <td class="detail_label">Score</td>
              <td><%= form.text_field :score, id: 'inning_score', class: 'ui mini input' %></td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <table class="ui attached very compact celled table" id="batting_table">
        <tbody>
          <tr id="batting-collapse-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="batting_collapse"><i class="large inverted white caret square up outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Batting Details</td>
          </tr>
          <tr id="batting-expand-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="batting_expand"><i class="large inverted white caret square down outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Batting Details</td>
          </tr>
          <tr id="batting_details_row">
            <table class="ui celled table" id="batting_details_table">
      <tr>
        <th>Batter</th>
        <th>Details</th>
        <th>How Out</th>
        <th>Fielder</th>
        <th>Bowler</th>
        <th>4s</th>
        <th>6s</th>
        <th>Runs</th>
      </tr>
      <tr>
        <td>01</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>02</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>03</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>04</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>05</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>06</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>07</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>08</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>09</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>10</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>11</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <table class="ui attached very compact celled table" id="fow_table">
        <tbody>
          <tr id="fow-collapse-row" class="detail_header_row">
            <th class="one wide"><a class="no-link" id="fow_collapse"><i class="large inverted white caret square up outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Fall Of Wickets</td>
          </tr>
          <tr id="fow-expand-row" class="detail_header_row">
            <th class="one wide"><a class="no-link" id="fow_expand"><i class="large inverted white caret square down outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Fall Of Wickets</td>
          </tr>
          <tr id="fow_details_row">
            <table class="ui definition celled table" id="fow_details_table">
          <tr align="center">
            <th></th>
            <th>01</th>
            <th>02</th>
            <th>03</th>
            <th>04</th>
            <th>05</th>
            <th>06</th>
            <th>07</th>
            <th>08</th>
            <th>09</th>
            <th>10</th>
          </tr>
          <tr align="center">
            <td class="one wide">Batter Out</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr align="center">
            <td>Not Out</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr align="center">
            <td>Score</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </table>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <table class="ui attached very compact celled table" id="bowling_table">
        <tbody>
          <tr id="bowling-collapse-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="bowling_collapse"><i class="large inverted white caret square up outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Bowling Details</td>
          </tr>
          <tr id="bowling-expand-row" class="detail_header_row">
            <td class="one wide"><a class="no-link" id="bowling_expand"><i class="large inverted white caret square down outline icon"></i></a></td>
            <td colspan=13 class="detail_header_text">Bowling Details</td>
          </tr>
          <tr id="bowling_details_row">
            <table class="ui celled table" id="bowling_details_table">
      <tr>
        <th>Bowler</th>
        <th>Details</th>
        <th>Overs</th>
        <th>Maidens</th>
        <th>Wides</th>
        <th>No Balls</th>
        <th>Byes</th>
        <th>Leg Byes</th>
        <th>Wickets</th>
        <th>Runs</th>
      </tr>
      <tr>
        <td>01</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>02</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>03</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>04</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>05</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>06</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>07</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>08</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>09</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
          </tr>
        </tbody>
      </table>
    </div>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/innings/edit.html.erb
<h1>Editing Inning</h1>

<%= render 'form', inning: @inning %>

<%= link_to 'Show', @inning %> |
<%= link_to 'Back', innings_path %>

app/views/innings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Innings</h1>

<table>
  <thead>
    <tr>
      <th>Inning no</th>
      <th>Batting team</th>
      <th>Bowling team</th>
      <th>Runs</th>
      <th>Wickets</th>
      <th>Byes</th>
      <th>Legbyes</th>
      <th>No balls</th>
      <th>Wides</th>
      <th>Score</th>
      <th>Match</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @innings.each do |inning| %>
      <tr>
        <td><%= inning.inning_no %></td>
        <td><%= inning.batting_team %></td>
        <td><%= inning.bowling_team %></td>
        <td><%= inning.runs %></td>
        <td><%= inning.wickets %></td>
        <td><%= inning.byes %></td>
        <td><%= inning.legbyes %></td>
        <td><%= inning.no_balls %></td>
        <td><%= inning.wides %></td>
        <td><%= inning.score %></td>
        <td><%= inning.match %></td>
        <td><%= link_to 'Show', inning %></td>
        <td><%= link_to 'Edit', edit_inning_path(inning) %></td>
        <td><%= link_to 'Destroy', inning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inning', new_inning_path %>

app/views/innings/new.html.erb
<%= render 'form', inning: @inning %>

app/views/innings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inning no:</strong>
  <%= @inning.inning_no %>
</p>

<p>
  <strong>Batting team:</strong>
  <%= @inning.batting_team %>
</p>

<p>
  <strong>Bowling team:</strong>
  <%= @inning.bowling_team %>
</p>

<p>
  <strong>Runs:</strong>
  <%= @inning.runs %>
</p>

<p>
  <strong>Wickets:</strong>
  <%= @inning.wickets %>
</p>

<p>
  <strong>Byes:</strong>
  <%= @inning.byes %>
</p>

<p>
  <strong>Legbyes:</strong>
  <%= @inning.legbyes %>
</p>

<p>
  <strong>No balls:</strong>
  <%= @inning.no_balls %>
</p>

<p>
  <strong>Wides:</strong>
  <%= @inning.wides %>
</p>

<p>
  <strong>Score:</strong>
  <%= @inning.score %>
</p>

<p>
  <strong>Match:</strong>
  <%= @inning.match %>
</p>

<%= link_to 'Edit', edit_inning_path(@inning) %> |
<%= link_to 'Back', innings_path %>