config/routes.rb
Rails.application.routes.draw do
  
  resources :innings
  #get 'match_players/index'

  #get 'match_players/show'

  get 'fixtures/index'

  get 'fixtures/show'
  
  get 'matches/all', to: 'matches#all'

  resources :matches
  resources :rounds
  # resources :comp_rounds
  resources :competitions, shallow: true do
    resources :rounds do
      resources :fixtures do
        resources :matches do
          resources :innings do
          
          end
        end  
      end
    end
  end
  resources :players
  resources :teams

  resources :clubs, shallow: true do
    resources :teams do
      resources :players
    end
    resources :players
  end
  resources :keywords
  #get 'static_pages/welcome'
  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    validates :name, :street_address, :street_city, :street_state, :phone, :email, presence: true
    mount_uploader :logo, LogoUploader

    has_many :teams
    has_many :players

    def display_address
      if self.street_address != nil then
        return self.street_address.to_s + ", " + self.street_city.to_s + ", " + self.street_state.to_s + ", " + self.street_postcode.to_s
      end
    end
    def display_post_address
      if self.postal_address != nil then
        return self.postal_address + ", " + self.postal_city + ", " + self.postal_state + ", " + self.postal_postcode
      end
    end
end

app/models/competition.rb
class Competition < ApplicationRecord
    validates :name, :start_date, :end_date, :match_days, presence: true

    has_many :rounds, inverse_of: :competition
    # has_many :matches
end

app/models/fixture.rb
class Fixture < ApplicationRecord
    validates :grade, :home_team, :away_team, presence: true
    
    belongs_to :round, inverse_of: :fixtures
    has_many :matches, inverse_of: :fixture
end

app/models/inning.rb
class Inning < ApplicationRecord
  validates :inning_no, :batting_team, :bowling_team, presence: true  
  
  belongs_to :match, inverse_of: :innings
  #has_many :overs
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :key_type, :key_value, presence: true

  def by_key(key)
      AdminKeyword.find_each do |keyword|
          keyword.find_by key_type: (key)
      end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :fixture, inverse_of: :matches
  
  has_many :innings
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
    validates :name, presence: true
    
    belongs_to :match
end

app/models/player.rb
class Player < ApplicationRecord
  validates :first_name, :last_name, :full_name, :display_name, :phone, :email, presence: :true

  belongs_to :club
  belongs_to :team

  # def club_name
  #   return Club.find_by_id(self.club_id).name
  # end
end

app/models/round.rb
class Round < ApplicationRecord
  validates :round_no, :start_date, :end_date, presence: true
  
  belongs_to :competition, inverse_of: :rounds
  has_many :fixtures, dependent: :destroy, inverse_of: :round
  accepts_nested_attributes_for :fixtures
  
  def all_matches
    self.fixtures.each do |fix|
      return fix.matches
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, :grade, presence: true

  belongs_to :club
  has_many :players
  
  # def club_name
  #   return Club.find(self.club_id).name
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def yesno_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/innings_helper.rb
module InningsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_sidemenu.html.erb
<div class="ui grid">
  <div class="four wide column">
    <div class="ui vertical menu">
      <span><%= link_to "Club", clubs_path, class: "item" %></span>
      <span><%= link_to "Teams", teams_path, class: "item" %></span>
      <span><%= link_to "Players", players_path, class: "item" %></span>
      <div class="ui divider"></div>
      <span><%= link_to "Competitions", competitions_path, class: "item" %></span>
      <span><%= link_to "Fixtures", clubs_path, class: "item" %></span>
      <div class="ui divider"></div>
      <span><%= link_to "Keywords", keywords_path, class: "item" %></span>
    </div>
  </div>
  <div class="twelve wide column">
    <%= yield %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyCricket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui blue inverted menu">

        <a href="/" class="header item">
          <%= image_tag "logo1.png", class: "logo" %>&nbsp;&nbsp;rubyCricket
        </a>
        <a href="/" class="item">Home</a>
        <div class="ui simple dropdown item">
          Administration <i class="dropdown icon"></i>
          <div class="menu">
            <%= link_to "Club", clubs_path, class: "item" %>
            <%= link_to "Teams", teams_path, class: "item" %>
            <%= link_to "Players", players_path, class: "item" %>
            <div class="divider"></div>
            <%= link_to "Competitions", competitions_path, class: "item" %>
            <a class="item" href="#">Fixtures</a>
            <div class="divider"></div>
            <a class="item" href="#">Keywords</a>
          </div>
        </div>

    </div>
    <%= yield %>
  </body>
</html>